# Example workflow
name: Format

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - name: Google Java Format Action
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace --aosp"
          #--aosp, -aosp, -a
          #  Use AOSP style instead of Google Style (4-space indentation).
          # Recommended if you use MacOS:
          githubToken: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any